- name: Set machine name
  ansible.builtin.shell: set-prompt Grafana

- name: copy grafana repo file
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install Grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: Start Grafana server
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes
    daemon-reload: yes