format_version: 10
pipelines:
  grafana:
    group: Tools
    materials:
      git-887d6e3:
        git: https://github.com/iteration-2/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: ["-i", "grafana-internal.pappik.online,", "tools.yml", "-e", "tool_name=grafana","-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}





#      - QA:
#          fetch_materials: true
#          environment_variables:
#            env: dev
#          approval:
#            type: manual
#            allow_only_on_success: false
#          jobs:
#            backend-setup:
#              timeout: 0
#              tasks:
#                - exec:
#                    command: bash
#                    arguments: [ "init", "-backend-config=env-dev/state.tfvars" ]
#
#                    run_if: passed
#
#      - STAGING:
#          fetch_materials: true
#          environment_variables:
#            env: dev
#          approval:
#            type: manual
#            allow_only_on_success: false
#          jobs:
#            backend-setup:
#              timeout: 0
#              tasks:
#                - exec:
#                    command: bash
#                    arguments: [ "init", "-backend-config=env-dev/state.tfvars" ]
#
#                    run_if: passed
#
#      - PROD:
#          fetch_materials: true
#          environment_variables:
#            env: dev
#          approval:
#            type: manual
#            allow_only_on_success: false
#          jobs:
#            backend-setup:
#              timeout: 0
#              tasks:
#                - exec:
#                    command: bash
#                    arguments: [ "init", "-backend-config=env-dev/state.tfvars" ]
#
#                    run_if: passed
