format_version: 10
pipelines:
  tools-tf-apply:
    group: Terraform
    materials:
      git-887d6e3:
        git: https://github.com/iteration-2/tools-automation.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Apply:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            terraform-apply-:
              tasks:
                - exec: {command: terraform, arguments: ["init" ], run_if: passed}
                - exec: { command: terraform, arguments: [ "destroy", "-auto-approve"], run_if: passed }


